//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecErrores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecErrores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RecErrores", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos! En este momento no podemos procesar su solicitud. &lt;p&gt;Por favor intente en unos minutos.&lt;p/&gt;.
        /// </summary>
        internal static string Err_0000 {
            get {
                return ResourceManager.GetString("Err_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Acceso denegado!.
        /// </summary>
        internal static string Err_401 {
            get {
                return ResourceManager.GetString("Err_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !La sesión ha expirado!.
        /// </summary>
        internal static string Err_403 {
            get {
                return ResourceManager.GetString("Err_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos! &lt;br/&gt;La página que está solicitando no se encuentra disponible.
        /// </summary>
        internal static string Err_404 {
            get {
                return ResourceManager.GetString("Err_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos! En este momento no podemos procesar su solicitud. &lt;p&gt;Por favor intente en unos minutos.&lt;p/&gt;.
        /// </summary>
        internal static string Err_500 {
            get {
                return ResourceManager.GetString("Err_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario es requerido.
        /// </summary>
        internal static string Err_AliasUsuarioRequerido {
            get {
                return ResourceManager.GetString("Err_AliasUsuarioRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La respuesta del captcha es incorrecta; por favor verifique..
        /// </summary>
        internal static string Err_CaptchaInvalido {
            get {
                return ResourceManager.GetString("Err_CaptchaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La respuesta del captcha no puede ser vacía.
        /// </summary>
        internal static string Err_CaptchaVacio {
            get {
                return ResourceManager.GetString("Err_CaptchaVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor confirmar contraseña.
        /// </summary>
        internal static string Err_ConfirmarRequerido {
            get {
                return ResourceManager.GetString("Err_ConfirmarRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña inválida.
        /// </summary>
        internal static string Err_ContrasenaRequerido {
            get {
                return ResourceManager.GetString("Err_ContrasenaRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su correo electrónico.
        /// </summary>
        internal static string Err_CorreoRequerido {
            get {
                return ResourceManager.GetString("Err_CorreoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique la sintaxis en su correo.
        /// </summary>
        internal static string Err_FormatoCorreo {
            get {
                return ResourceManager.GetString("Err_FormatoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de la fecha es requerido.
        /// </summary>
        internal static string Err_FormatoFechaRequerido {
            get {
                return ResourceManager.GetString("Err_FormatoFechaRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el idioma de su preferencia.
        /// </summary>
        internal static string Err_IdiomaRequerido {
            get {
                return ResourceManager.GetString("Err_IdiomaRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticación fallida.
        /// </summary>
        internal static string Err_LogFallido {
            get {
                return ResourceManager.GetString("Err_LogFallido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defina una cantidad de decimales.
        /// </summary>
        internal static string Err_NumDecimalesRequerido {
            get {
                return ResourceManager.GetString("Err_NumDecimalesRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token requerido.
        /// </summary>
        internal static string Err_OtpRequerido {
            get {
                return ResourceManager.GetString("Err_OtpRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el país.
        /// </summary>
        internal static string Err_PaisRequerido {
            get {
                return ResourceManager.GetString("Err_PaisRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has respondido mas de una vez a alguna pregunta.
        /// </summary>
        internal static string Err_RegistrarPreguntas {
            get {
                return ResourceManager.GetString("Err_RegistrarPreguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos: usuario no encontrado.
        /// </summary>
        internal static string Err_RenovarContrasenaPaso1 {
            get {
                return ResourceManager.GetString("Err_RenovarContrasenaPaso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una o más respuestas incorrectas.
        /// </summary>
        internal static string Err_RenovarContrasenaPaso2 {
            get {
                return ResourceManager.GetString("Err_RenovarContrasenaPaso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string Err_Requerido {
            get {
                return ResourceManager.GetString("Err_Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Si o No requiere token.
        /// </summary>
        internal static string Err_RequiereOTPRequerido {
            get {
                return ResourceManager.GetString("Err_RequiereOTPRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesaria una respuesta.
        /// </summary>
        internal static string Err_RespuestaRequerido {
            get {
                return ResourceManager.GetString("Err_RespuestaRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar un separador de decimales.
        /// </summary>
        internal static string Err_SepDecimalRequerido {
            get {
                return ResourceManager.GetString("Err_SepDecimalRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indiar un separador de miles.
        /// </summary>
        internal static string Err_SepMilesRequerido {
            get {
                return ResourceManager.GetString("Err_SepMilesRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una o más preguntas invalidas verifique su selección.
        /// </summary>
        internal static string Err_UnaMasPreguntasInvalidas {
            get {
                return ResourceManager.GetString("Err_UnaMasPreguntasInvalidas", resourceCulture);
            }
        }
    }
}
