//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecEtiquetas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecEtiquetas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RecEtiquetas", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        internal static string AppLogin {
            get {
                return ResourceManager.GetString("AppLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string AppLogout {
            get {
                return ResourceManager.GetString("AppLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi cuenta.
        /// </summary>
        internal static string AppMyAccount {
            get {
                return ResourceManager.GetString("AppMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string App_Aceptar {
            get {
                return ResourceManager.GetString("App_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de contraseña.
        /// </summary>
        internal static string App_CambioDeContrasena {
            get {
                return ResourceManager.GetString("App_CambioDeContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string App_Cancelar {
            get {
                return ResourceManager.GetString("App_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su contraseña va a vencer en {0} días, &lt;br/&gt;¿Desea modificarla ahora?.
        /// </summary>
        internal static string App_ContrasenaPorVencer {
            get {
                return ResourceManager.GetString("App_ContrasenaPorVencer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su contraseña ha vencido, por favor introduzca su nueva contraseña..
        /// </summary>
        internal static string App_ContrasenaVencida {
            get {
                return ResourceManager.GetString("App_ContrasenaVencida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rica.
        /// </summary>
        internal static string App_CostaRica {
            get {
                return ResourceManager.GetString("App_CostaRica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los derechos reservados.
        /// </summary>
        internal static string App_DerechosReservados {
            get {
                return ResourceManager.GetString("App_DerechosReservados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string App_Entrar {
            get {
                return ResourceManager.GetString("App_Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el código de 6 dígitos generado:.
        /// </summary>
        internal static string App_IngreseCodigoGenerado {
            get {
                return ResourceManager.GetString("App_IngreseCodigoGenerado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese OTP.
        /// </summary>
        internal static string App_IngreseOTP {
            get {
                return ResourceManager.GetString("App_IngreseOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargue el app Google Authenticator..
        /// </summary>
        internal static string App_IntruccionOtp1 {
            get {
                return ResourceManager.GetString("App_IntruccionOtp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija uno de los pasos para continuar:.
        /// </summary>
        internal static string App_IntruccionOtp2 {
            get {
                return ResourceManager.GetString("App_IntruccionOtp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite los números que aparecen en su celular. No incluya espacios..
        /// </summary>
        internal static string App_IntruccionOtp3 {
            get {
                return ResourceManager.GetString("App_IntruccionOtp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escaneé el siguiente QR Code con la aplicación Google Authenticator..
        /// </summary>
        internal static string App_IntruccionOtpA1 {
            get {
                return ResourceManager.GetString("App_IntruccionOtpA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número que aparece en su celular digítelo en el paso #3..
        /// </summary>
        internal static string App_IntruccionOtpA2 {
            get {
                return ResourceManager.GetString("App_IntruccionOtpA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abra Google Authenticator y digite el siguiente código en su celular..
        /// </summary>
        internal static string App_IntruccionOtpB1 {
            get {
                return ResourceManager.GetString("App_IntruccionOtpB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número que aparece en su celular digítelo en el paso #3..
        /// </summary>
        internal static string App_IntruccionOtpB2 {
            get {
                return ResourceManager.GetString("App_IntruccionOtpB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONIBYTE.
        /// </summary>
        internal static string App_Monibyte {
            get {
                return ResourceManager.GetString("App_Monibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaragua.
        /// </summary>
        internal static string App_Nicaragua {
            get {
                return ResourceManager.GetString("App_Nicaragua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string App_No {
            get {
                return ResourceManager.GetString("App_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidó su contraseña?.
        /// </summary>
        internal static string App_Olvido {
            get {
                return ResourceManager.GetString("App_Olvido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panamá.
        /// </summary>
        internal static string App_Panama {
            get {
                return ResourceManager.GetString("App_Panama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba los 6 números.
        /// </summary>
        internal static string App_PlaceHolderOTP {
            get {
                return ResourceManager.GetString("App_PlaceHolderOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to República Dominicana.
        /// </summary>
        internal static string App_RepDominicana {
            get {
                return ResourceManager.GetString("App_RepDominicana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación realizada con éxito.
        /// </summary>
        internal static string App_ResultadoExitoso {
            get {
                return ResourceManager.GetString("App_ResultadoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanee o ingrese el siguiente código:.
        /// </summary>
        internal static string App_ScaneeIngreseCodigo {
            get {
                return ResourceManager.GetString("App_ScaneeIngreseCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el país(es).
        /// </summary>
        internal static string App_SeleccionePais {
            get {
                return ResourceManager.GetString("App_SeleccionePais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una pregunta.
        /// </summary>
        internal static string App_SeleccioneUnaPregunta {
            get {
                return ResourceManager.GetString("App_SeleccioneUnaPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione idioma.
        /// </summary>
        internal static string App_SeleccionIdioma {
            get {
                return ResourceManager.GetString("App_SeleccionIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección de preguntas.
        /// </summary>
        internal static string App_SeleccionPreguntas {
            get {
                return ResourceManager.GetString("App_SeleccionPreguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string App_Si {
            get {
                return ResourceManager.GetString("App_Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        internal static string App_Siguiente {
            get {
                return ResourceManager.GetString("App_Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalice el uso de cada tarjeta titular y sus adicionales. Administre los límites de crédito y realice cambios grupales en la configuración de las cuentas.
        /// </summary>
        internal static string App_TextoPauta1 {
            get {
                return ResourceManager.GetString("App_TextoPauta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vamos a otorgarles el poder a ustedes de manejar sus medios de pago efectivamente  y de manera segura, lo que reducirá la dependencia de los bancos, les hará la vida mucho más fácil y les generará ahorros importantes.
        /// </summary>
        internal static string App_TextoPauta2 {
            get {
                return ResourceManager.GetString("App_TextoPauta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONIBYTE nació para proveer una solución tecnológica para Banco Lafise. Esta solución se convertirá en una gran ventaja competitiva y revolucionará la industria de Medios de Pago en las empresas.
        /// </summary>
        internal static string App_TextoPauta3 {
            get {
                return ResourceManager.GetString("App_TextoPauta3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A través de nuestra plataforma digital, le ofrecemos soluciones a la medida de los requerimientos de su empresa.  &lt;br/&gt; &lt;br/&gt; Puede acceder a esta herramienta desde su computadora ó dispositivo móvil y personalizar
        ///            los parámetros de sus tarjetas de crédito, definir límites de crédito, condiciones de uso
        ///            y restricciones para cada uno de sus colaboradores.
        /// </summary>
        internal static string App_TextoPrincipal {
            get {
                return ResourceManager.GetString("App_TextoPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o alias de su preferencia.
        /// </summary>
        internal static string App_UsuarioAliasDePreferencia {
            get {
                return ResourceManager.GetString("App_UsuarioAliasDePreferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver más....
        /// </summary>
        internal static string App_VerMas {
            get {
                return ResourceManager.GetString("App_VerMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 mes.
        /// </summary>
        internal static string App_VigenciaMensual {
            get {
                return ResourceManager.GetString("App_VigenciaMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 meses.
        /// </summary>
        internal static string App_VigenciaSemestral {
            get {
                return ResourceManager.GetString("App_VigenciaSemestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 meses.
        /// </summary>
        internal static string App_VigenciaTrimestral {
            get {
                return ResourceManager.GetString("App_VigenciaTrimestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitud mínima 4 caracteres.
        /// </summary>
        internal static string Ayu_Alias {
            get {
                return ResourceManager.GetString("Ayu_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su usuario.
        /// </summary>
        internal static string Ayu_AliasUsuario {
            get {
                return ResourceManager.GetString("Ayu_AliasUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;ayuda-formulario&quot;&gt;*Favor ingrese su actual contraseña. *Posteriormente ingrese la nueva contraseña.
        ///    *Luego confirme la nueva contraseña.&lt;br /&gt; *La contraseña debe de poseer mínimo 8 caracteres. *Y mínimo 2 números y 4 letras.&lt;br /&gt; *El máximo es de 16 caracteres.&lt;/div&gt;.
        /// </summary>
        internal static string Ayu_CambioContrasena {
            get {
                return ResourceManager.GetString("Ayu_CambioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme su contraseña.
        /// </summary>
        internal static string Ayu_Confirmar {
            get {
                return ResourceManager.GetString("Ayu_Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su contraseña, utilice números y letras preferiblemente..
        /// </summary>
        internal static string Ayu_Contrasena {
            get {
                return ResourceManager.GetString("Ayu_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar de forma correcta su correo electrónico registrado.
        /// </summary>
        internal static string Ayu_Correo {
            get {
                return ResourceManager.GetString("Ayu_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar de forma correcta su correo electrónico de preferencia.
        /// </summary>
        internal static string Ayu_CorreoRegistrar {
            get {
                return ResourceManager.GetString("Ayu_CorreoRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione su  idioma de preferencia.
        /// </summary>
        internal static string Ayu_Idioma {
            get {
                return ResourceManager.GetString("Ayu_Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione su país.
        /// </summary>
        internal static string Ayu_Pais {
            get {
                return ResourceManager.GetString("Ayu_Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;ayuda-formulario&quot;&gt;*La contraseña debe de poseer mínimo 8 caracteres. &lt;br /&gt;*Y mínimo 2 números y 4 letras.&lt;br /&gt; *El máximo es de 16 caracteres.&lt;/div&gt;.
        /// </summary>
        internal static string Ayu_RenuevaContrasena {
            get {
                return ResourceManager.GetString("Ayu_RenuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string Mod_AliasUsuario {
            get {
                return ResourceManager.GetString("Mod_AliasUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string Mod_Confirmar {
            get {
                return ResourceManager.GetString("Mod_Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string Mod_Contrasena {
            get {
                return ResourceManager.GetString("Mod_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual.
        /// </summary>
        internal static string Mod_ContrasenaActual {
            get {
                return ResourceManager.GetString("Mod_ContrasenaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string Mod_Correo {
            get {
                return ResourceManager.GetString("Mod_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de fecha:.
        /// </summary>
        internal static string Mod_FormatoFecha {
            get {
                return ResourceManager.GetString("Mod_FormatoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite selección movimientos en liquidación gastos:.
        /// </summary>
        internal static string Mod_IdDesmarcableMovLiq {
            get {
                return ResourceManager.GetString("Mod_IdDesmarcableMovLiq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar estado de cuenta individual:.
        /// </summary>
        internal static string Mod_IdEnviaEstCtaIndividual {
            get {
                return ResourceManager.GetString("Mod_IdEnviaEstCtaIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir  débito y crédito en movimientos de efectivo :.
        /// </summary>
        internal static string Mod_IdIncluyeDebCred {
            get {
                return ResourceManager.GetString("Mod_IdIncluyeDebCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibir notificación diaria de denegaciones:.
        /// </summary>
        internal static string Mod_IdInfDenegaciones {
            get {
                return ResourceManager.GetString("Mod_IdInfDenegaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar aprobación mancomunada:.
        /// </summary>
        internal static string Mod_IdRequiereAutorizacion {
            get {
                return ResourceManager.GetString("Mod_IdRequiereAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restringe inclusión movimientos en liquidación gastos:.
        /// </summary>
        internal static string Mod_IdValidaEdicionMov {
            get {
                return ResourceManager.GetString("Mod_IdValidaEdicionMov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        internal static string Mod_NuevaContrasena {
            get {
                return ResourceManager.GetString("Mod_NuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de decimales:.
        /// </summary>
        internal static string Mod_NumDecimales {
            get {
                return ResourceManager.GetString("Mod_NumDecimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        internal static string Mod_OTP {
            get {
                return ResourceManager.GetString("Mod_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string Mod_Pais {
            get {
                return ResourceManager.GetString("Mod_Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerir Token.
        /// </summary>
        internal static string Mod_RequieresOTP {
            get {
                return ResourceManager.GetString("Mod_RequieresOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta.
        /// </summary>
        internal static string Mod_Respuesta {
            get {
                return ResourceManager.GetString("Mod_Respuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separador de decimales:.
        /// </summary>
        internal static string Mod_SepDecimal {
            get {
                return ResourceManager.GetString("Mod_SepDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separador de miles:.
        /// </summary>
        internal static string Mod_SepMiles {
            get {
                return ResourceManager.GetString("Mod_SepMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia.
        /// </summary>
        internal static string Mod_VigenciaContrasena {
            get {
                return ResourceManager.GetString("Mod_VigenciaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string Navigation_Link0 {
            get {
                return ResourceManager.GetString("Navigation_Link0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nosotros.
        /// </summary>
        internal static string Navigation_Link1 {
            get {
                return ResourceManager.GetString("Navigation_Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjetas.
        /// </summary>
        internal static string Navigation_Link2 {
            get {
                return ResourceManager.GetString("Navigation_Link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        internal static string Navigation_Link3 {
            get {
                return ResourceManager.GetString("Navigation_Link3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paso 1/3 - Autenticación.
        /// </summary>
        internal static string Tit_Autenticar {
            get {
                return ResourceManager.GetString("Tit_Autenticar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a Monibyte.
        /// </summary>
        internal static string Tit_BienvenidoMonibyte {
            get {
                return ResourceManager.GetString("Tit_BienvenidoMonibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información personal.
        /// </summary>
        internal static string Tit_InfoPersonal {
            get {
                return ResourceManager.GetString("Tit_InfoPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        internal static string Tit_Ingresar {
            get {
                return ResourceManager.GetString("Tit_Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el código Token generado con el Google Authenticator..
        /// </summary>
        internal static string Tit_IngresoOtp {
            get {
                return ResourceManager.GetString("Tit_IngresoOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el código Token generado con el Google Authenticator..
        /// </summary>
        internal static string Tit_InstrucionesIngresoOtp {
            get {
                return ResourceManager.GetString("Tit_InstrucionesIngresoOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siga los siguientes pasos para activar el Token por primera vez:.
        /// </summary>
        internal static string Tit_InstrucionesOtp {
            get {
                return ResourceManager.GetString("Tit_InstrucionesOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INNOVACIÓN en medios de pago electrónicos.
        /// </summary>
        internal static string Tit_LemaMonibyte {
            get {
                return ResourceManager.GetString("Tit_LemaMonibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paso 3/3 - Nueva Contraseña.
        /// </summary>
        internal static string Tit_NuevaContrasena {
            get {
                return ResourceManager.GetString("Tit_NuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paso 2/3 - Responda las Preguntas.
        /// </summary>
        internal static string Tit_RespondaPreguntas {
            get {
                return ResourceManager.GetString("Tit_RespondaPreguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija una empresa.
        /// </summary>
        internal static string Tit_SeleccionEmpresa {
            get {
                return ResourceManager.GetString("Tit_SeleccionEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monibyte es seguridad, flexibilidad, tecnología y control.
        /// </summary>
        internal static string Tit_SubTituloBody {
            get {
                return ResourceManager.GetString("Tit_SubTituloBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una herramienta de control.
        /// </summary>
        internal static string Tit_Titulopauta1 {
            get {
                return ResourceManager.GetString("Tit_Titulopauta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestra propuesta de valor.
        /// </summary>
        internal static string Tit_Titulopauta2 {
            get {
                return ResourceManager.GetString("Tit_Titulopauta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con el respaldo de LAFISE.
        /// </summary>
        internal static string Tit_Titulopauta3 {
            get {
                return ResourceManager.GetString("Tit_Titulopauta3", resourceCulture);
            }
        }
    }
}
